service: ohys-search
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  app:
    handler: src/serverless.handler
    events:
      - httpApi: '*'
      - httpApi:
          path: /{any+}
          method: '*'
