name = "ohys-search"
type = "javascript"
route = ''
# zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-28"

[build]
command = "yarn workers:build"

[build.upload]
format = "service-worker"