name: deploy

on:
  push:
    branches: [main]

jobs:
  serverless:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Deploy
        run: yarn deploy:prod
